### ISSUE TITLE
Use onxxxx not _onxxxx in render string, it's more nature.

### ISSUE THREAD

**Issue by lunny** [murlokswarm/markup#13]
Since all the [events](https://github.com/murlokswarm/app/wiki/Component#eventhandlers) begins with `on` so that it's no need to add `_` before `on`, You just need to  change https://github.com/murlokswarm/markup/blob/master/node.go#L150 and https://github.com/murlokswarm/markup/blob/master/node.go#L99 the two lines.

**Comment by maxence-charriere** [comment]
Totally agree with that.
The reason of the ```_``` was that the package is pretty young and there is some stuff which would still require the use of javascript.
Did not want to cut the standard behavior.

If other have an opinion on it feel free to comment.
Also let met think a little of what it would take to do this change.
Will come back to you soon.

thanks for https://github.com/murlokswarm/markup/pull/15

**Comment by maxence-charriere** [comment]
Alright, after all... the goal is to not use js at all. If there is some need we will figure out a way to do everything with Go.

**Comment by lunny** [comment]
Then,
1. You could call javascript on component methods, but how?
2. And maybe you could set a coup of default events method so that you could not need to write many event attribute tag on `div`, e.g

```Go
type Hello struct {
}

func (h *Hello) OnMouseOver(arg app.MouseArg) {
}

func (h *Hello) Render() string {
    return `
<div>
</div>
`
}
```

Since `onmouseover` is default mapping to `OnMouseOver`, then you can don't declare the `onmouseover` on the `div` except you use another method name.

**Comment by lunny** [comment]
Or something others `<div onmouseover="javascript:alert(1)"></div>` this will run in client side, but `<div onmouseover="go:OnMouseOver"></div>` this will run in server side.

**Comment by maxence-charriere** [comment]
I like the idea that go is the default behavior.
Let's keep it like that for the moment.
Can still declare a script tag if javascript is needed.

**Comment by maxence-charriere** [comment]
https://github.com/murlokswarm/markup/pull/15 has been merged.

**Comment by lunny** [comment]
Added #17 and #18
